-- ─────────────────────────────────────────────────────────────────────────────
-- RLS performance pass — (SELECT auth.uid()) wrapping + composite indexes
--
-- Two findings from the DBA audit:
--
--   H1. Every tenant-isolation policy in 20260515_multi_tenant.sql calls
--       get_current_tenant_id() / get_current_user_role() directly. Postgres
--       can't see these as STABLE for RLS short-circuiting → the function
--       is re-evaluated per row. Wrapping in (SELECT …) forces a single
--       evaluation per statement.
--
--   H2. Composite indexes are missing for hot RLS predicates:
--         items(tenant_id, status)              ← storefront + active-items lists
--         sales_orders(tenant_id, created_at DESC) ← monthly-limit trigger
--         subscription_payments(tenant_id, status) ← admin pending-review list
--         stock_in_movements(tenant_id, item_id)
--         stock_out_movements(tenant_id, item_id)
--
-- This migration rewrites the tenant_isolation_* policies and adds the
-- missing indexes. The rewrite is mechanical — same predicates, just
-- wrapped — so behavior is unchanged.
-- ─────────────────────────────────────────────────────────────────────────────

BEGIN;

-- ============================================================================
-- 1. Rewrite tenant-isolation policies for the 7 main data tables
-- ============================================================================
DO $$
DECLARE
  tbl TEXT;
BEGIN
  FOREACH tbl IN ARRAY ARRAY[
    'suppliers','items','stock_in','stock_out',
    'purchase_invoices','sales_orders','store_profiles'
  ]
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS "tenant_isolation_%1$s_select" ON %1$s;', tbl);
    EXECUTE format('DROP POLICY IF EXISTS "tenant_isolation_%1$s_insert" ON %1$s;', tbl);
    EXECUTE format('DROP POLICY IF EXISTS "tenant_isolation_%1$s_update" ON %1$s;', tbl);
    EXECUTE format('DROP POLICY IF EXISTS "tenant_isolation_%1$s_delete" ON %1$s;', tbl);

    EXECUTE format($fmt$
        CREATE POLICY "tenant_isolation_%1$s_select" ON %1$s
          FOR SELECT TO authenticated
          USING (
            tenant_id = (SELECT get_current_tenant_id())
            OR (SELECT get_current_user_role()) = 'super_admin'
          );

        CREATE POLICY "tenant_isolation_%1$s_insert" ON %1$s
          FOR INSERT TO authenticated
          WITH CHECK (tenant_id = (SELECT get_current_tenant_id()));

        CREATE POLICY "tenant_isolation_%1$s_update" ON %1$s
          FOR UPDATE TO authenticated
          USING (tenant_id = (SELECT get_current_tenant_id()))
          WITH CHECK (tenant_id = (SELECT get_current_tenant_id()));

        CREATE POLICY "tenant_isolation_%1$s_delete" ON %1$s
          FOR DELETE TO authenticated
          USING (
            tenant_id = (SELECT get_current_tenant_id())
            OR (SELECT get_current_user_role()) = 'super_admin'
          );
      $fmt$,
      tbl
    );
  END LOOP;
END $$;

-- ============================================================================
-- 2. Rewrite the per-table policies that weren't generated by the loop
-- ============================================================================
-- tenants
DROP POLICY IF EXISTS "tenant_read_own" ON tenants;
CREATE POLICY "tenant_read_own" ON tenants
  FOR SELECT TO authenticated
  USING (
    id = (SELECT get_current_tenant_id())
    OR (SELECT get_current_user_role()) = 'super_admin'
  );

-- user_profiles
DROP POLICY IF EXISTS "tenant_admin_manage_users" ON user_profiles;
CREATE POLICY "tenant_admin_manage_users" ON user_profiles
  FOR ALL TO authenticated
  USING (
    tenant_id = (SELECT get_current_tenant_id())
    AND (SELECT get_current_user_role()) IN ('tenant_admin', 'super_admin')
  )
  WITH CHECK (
    tenant_id = (SELECT get_current_tenant_id())
    AND (SELECT get_current_user_role()) IN ('tenant_admin', 'super_admin')
  );

DROP POLICY IF EXISTS "user_read_own_profile" ON user_profiles;
CREATE POLICY "user_read_own_profile" ON user_profiles
  FOR SELECT TO authenticated
  USING (id = (SELECT auth.uid()));

-- subscription_events
DROP POLICY IF EXISTS "tenant_read_own_events" ON subscription_events;
CREATE POLICY "tenant_read_own_events" ON subscription_events
  FOR SELECT TO authenticated
  USING (tenant_id = (SELECT get_current_tenant_id()));

-- ============================================================================
-- 3. Composite indexes for hot RLS predicates
-- ============================================================================
-- Storefront + items lists: WHERE tenant_id = ? AND status = 'ACTIVE'
CREATE INDEX IF NOT EXISTS idx_items_tenant_status
  ON items (tenant_id, status);

-- Monthly order-limit trigger: WHERE tenant_id = ? AND created_at >= …
CREATE INDEX IF NOT EXISTS idx_sales_orders_tenant_created
  ON sales_orders (tenant_id, created_at DESC);

-- Super-admin pending payments list
CREATE INDEX IF NOT EXISTS idx_subscription_payments_tenant_status
  ON subscription_payments (tenant_id, status);

-- Movements joined by item (current_stock_view derivation, item history pages)
CREATE INDEX IF NOT EXISTS idx_stock_in_movements_tenant_item
  ON stock_in_movements (tenant_id, item_id);

CREATE INDEX IF NOT EXISTS idx_stock_out_movements_tenant_item
  ON stock_out_movements (tenant_id, item_id);

-- Purchase invoices by supplier within tenant (Suppliers detail page)
CREATE INDEX IF NOT EXISTS idx_purchase_invoices_tenant_supplier
  ON purchase_invoices (tenant_id, supplier_id);

-- Audit log lookups by actor's tenant (super admin investigations)
-- audit_log doesn't have tenant_id; target_id index from migration 23 covers
-- the "what happened to this tenant?" query.

-- ============================================================================
-- 4. Audit
-- ============================================================================
INSERT INTO audit_log (actor_id, actor_role, action, target_type, payload)
VALUES (
  NULL, 'system',
  'migration.rls_perf_applied',
  'rls_policies',
  jsonb_build_object(
    'tables', jsonb_build_array(
      'suppliers','items','stock_in','stock_out',
      'purchase_invoices','sales_orders','store_profiles',
      'tenants','user_profiles','subscription_events'
    ),
    'indexes_added', 6,
    'applied_at', now()
  )
);

COMMIT;
